{{- $exposedContainers := list }}
{{- range .Values.containers }}
  {{- if .expose }}
    {{- $exposedContainers = append $exposedContainers . }}
  {{- end }}
{{- end }}
{{- if and .Values.ingress.enabled $exposedContainers }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- $first := true }}
          {{- range $exposedContainers }}
          {{- if or .ingressPath $first }}
          - path: {{ .ingressPath | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.name }}
                port:
                  number: {{ .servicePort | default .port }}
          {{- end }}
          {{- $first = false }}
          {{- end }}
{{- end }}
