{{- $primaryContainer := index .Values.containers 0 }}
{{- if $primaryContainer.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: {{ $primaryContainer.port }}
      protocol: TCP
{{- end }}
