{{- $exposedContainers := list }}
{{- range .Values.containers }}
  {{- if .expose }}
    {{- $exposedContainers = append $exposedContainers . }}
  {{- end }}
{{- end }}
{{- if $exposedContainers }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "generic-app.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $exposedContainers }}
    - name: {{ .name }}
      port: {{ .servicePort | default .port }}
      targetPort: {{ .port }}
      protocol: TCP
    {{- end }}
{{- end }}
